.TH "StdColor" 3 "Thu Nov 20 2025 20:34:26" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdColor \- 预定义颜色（130 色）  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
预定义颜色（130 色） 


.PP
\fBSee also\fP
.RS 4
\fBBasic\&.h\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
