.TH "D:/Coding/S3GF/src/MultiThread/ThreadPool.h" 3 "Thu Nov 20 2025 20:40:12" "Version v0.1.0-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Coding/S3GF/src/MultiThread/ThreadPool.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Libs\&.h'\fP
.br
\fR#include 'Utils/Logger\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBS3GF::ThreadPool\fP"
.br
.ti -1c
.RI "class \fBS3GF::TasksManager\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TasksManager::Task\fP"
.br
.ti -1c
.RI "struct \fBS3GF::TasksManager::TaskCmp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBS3GF\fP"
.br
.RI "\fBS3GF\fP 空间 "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsleep\fP(sec)"
.br
.ti -1c
.RI "#define \fBsleepMS\fP(millisec)"
.br
.ti -1c
.RI "#define \fBsleepNS\fP(nanosec)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define sleep( sec)"
\fBValue:\fP
.nf
std::this_thread::sleep_for(std::chrono::seconds(sec))
.PP
.fi

.SS "#define sleepMS( millisec)"
\fBValue:\fP
.nf
std::this_thread::sleep_for(std::chrono::milliseconds(millisec))
.PP
.fi

.SS "#define sleepNS( nanosec)"
\fBValue:\fP
.nf
std::this_thread::sleep_for(std::chrono::nanoseconds(nanosec))
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
