.TH "S3GF" 3 "Version v0.0.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF \- \fBS3GF\fP 空间  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioSystem\fP"
.br
.ti -1c
.RI "class \fBCursor\fP"
.br
.RI "鼠标光标 "
.ti -1c
.RI "class \fBDateTime\fP"
.br
.ti -1c
.RI "class \fBEngine\fP"
.br
.ti -1c
.RI "class \fBEventSystem\fP"
.br
.ti -1c
.RI "class \fBFont\fP"
.br
.ti -1c
.RI "struct \fBGeometry\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "struct \fBGeometryF\fP"
.br
.RI "位置、大小 "
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "struct \fBMatrix2D\fP"
.br
.RI "二维矩阵 "
.ti -1c
.RI "struct \fBProperty\fP"
.br
.ti -1c
.RI "class \fBRandomGenerator\fP"
.br
.ti -1c
.RI "class \fBRenderer\fP"
.br
.ti -1c
.RI "struct \fBSize\fP"
.br
.RI "尺寸、大小 "
.ti -1c
.RI "class \fBTaskQueue\fP"
.br
.ti -1c
.RI "class \fBTextSystem\fP"
.br
.ti -1c
.RI "class \fBTexture\fP"
.br
.ti -1c
.RI "class \fBTimer\fP"
.br
.ti -1c
.RI "class \fBTrigger\fP"
.br
.ti -1c
.RI "struct \fBVector2\fP"
.br
.RI "向量坐标 "
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBS3GF\fP 空间 

所有库都将被存储于此命名空间 
.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
