.TH "S3GF::Geometry" 3 "Version v0.0.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::Geometry \- 位置、大小  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Basic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeometry\fP (int x, int y, int width, int height)"
.br
.ti -1c
.RI "void \fBsetGeometry\fP (int x, int y, int width, int height)"
.br
.ti -1c
.RI "void \fBsetPosition\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBresize\fP (int width, int height)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
位置、大小 

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
