.TH "S3GF::AudioSystem::Audio" 3 "Version v0.0.1-beta" "S3GF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S3GF::AudioSystem::Audio
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MIX_Audio * \fBself\fP"
.br
.ti -1c
.RI "Status \fBstatus\fP"
.br
.ti -1c
.RI "std::string \fBurl\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   MIX_Track * \fBself\fP {nullptr}"
.br
.ti -1c
.RI "   uint64_t \fBduration\fP {0}"
.br
.ti -1c
.RI "   uint64_t \fBposition\fP {0}"
.br
.ti -1c
.RI "} \fBtrack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for S3GF from the source code\&.
